/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as EventRouteImport } from './routes/event'
import { Route as DirektoriRouteImport } from './routes/direktori'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ArtikelRouteImport } from './routes/artikel'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as UmkmSlugRouteImport } from './routes/umkm.$slug'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminHeroRouteImport } from './routes/admin.hero'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated.dashboard.index'
import { Route as AuthenticatedDashboardProfilRouteImport } from './routes/_authenticated.dashboard.profil'
import { Route as AuthenticatedDashboardProdukRouteImport } from './routes/_authenticated.dashboard.produk'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const EventRoute = EventRouteImport.update({
  id: '/event',
  path: '/event',
  getParentRoute: () => rootRouteImport,
} as any)
const DirektoriRoute = DirektoriRouteImport.update({
  id: '/direktori',
  path: '/direktori',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtikelRoute = ArtikelRouteImport.update({
  id: '/artikel',
  path: '/artikel',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const UmkmSlugRoute = UmkmSlugRouteImport.update({
  id: '/umkm/$slug',
  path: '/umkm/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminHeroRoute = AdminHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProfilRoute =
  AuthenticatedDashboardProfilRouteImport.update({
    id: '/profil',
    path: '/profil',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardProdukRoute =
  AuthenticatedDashboardProdukRouteImport.update({
    id: '/produk',
    path: '/produk',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/direktori': typeof DirektoriRoute
  '/event': typeof EventRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/umkm/$slug': typeof UmkmSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/produk': typeof AuthenticatedDashboardProdukRoute
  '/dashboard/profil': typeof AuthenticatedDashboardProfilRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/direktori': typeof DirektoriRoute
  '/event': typeof EventRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/hero': typeof AdminHeroRoute
  '/admin/login': typeof AdminLoginRoute
  '/umkm/$slug': typeof UmkmSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard/produk': typeof AuthenticatedDashboardProdukRoute
  '/dashboard/profil': typeof AuthenticatedDashboardProfilRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/artikel': typeof ArtikelRoute
  '/auth': typeof AuthRoute
  '/direktori': typeof DirektoriRoute
  '/event': typeof EventRoute
  '/marketplace': typeof MarketplaceRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/admin/hero': typeof AdminHeroRoute
  '/admin_/login': typeof AdminLoginRoute
  '/umkm/$slug': typeof UmkmSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/_authenticated/dashboard/produk': typeof AuthenticatedDashboardProdukRoute
  '/_authenticated/dashboard/profil': typeof AuthenticatedDashboardProfilRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/artikel'
    | '/auth'
    | '/direktori'
    | '/event'
    | '/marketplace'
    | '/sitemap.xml'
    | '/dashboard'
    | '/admin/hero'
    | '/admin/login'
    | '/umkm/$slug'
    | '/admin/'
    | '/dashboard/produk'
    | '/dashboard/profil'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artikel'
    | '/auth'
    | '/direktori'
    | '/event'
    | '/marketplace'
    | '/sitemap.xml'
    | '/admin/hero'
    | '/admin/login'
    | '/umkm/$slug'
    | '/admin'
    | '/dashboard/produk'
    | '/dashboard/profil'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/artikel'
    | '/auth'
    | '/direktori'
    | '/event'
    | '/marketplace'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/admin/hero'
    | '/admin_/login'
    | '/umkm/$slug'
    | '/admin/'
    | '/_authenticated/dashboard/produk'
    | '/_authenticated/dashboard/profil'
    | '/_authenticated/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  ArtikelRoute: typeof ArtikelRoute
  AuthRoute: typeof AuthRoute
  DirektoriRoute: typeof DirektoriRoute
  EventRoute: typeof EventRoute
  MarketplaceRoute: typeof MarketplaceRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminLoginRoute: typeof AdminLoginRoute
  UmkmSlugRoute: typeof UmkmSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event': {
      id: '/event'
      path: '/event'
      fullPath: '/event'
      preLoaderRoute: typeof EventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direktori': {
      id: '/direktori'
      path: '/direktori'
      fullPath: '/direktori'
      preLoaderRoute: typeof DirektoriRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artikel': {
      id: '/artikel'
      path: '/artikel'
      fullPath: '/artikel'
      preLoaderRoute: typeof ArtikelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/umkm/$slug': {
      id: '/umkm/$slug'
      path: '/umkm/$slug'
      fullPath: '/umkm/$slug'
      preLoaderRoute: typeof UmkmSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/hero': {
      id: '/admin/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminHeroRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/profil': {
      id: '/_authenticated/dashboard/profil'
      path: '/profil'
      fullPath: '/dashboard/profil'
      preLoaderRoute: typeof AuthenticatedDashboardProfilRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/produk': {
      id: '/_authenticated/dashboard/produk'
      path: '/produk'
      fullPath: '/dashboard/produk'
      preLoaderRoute: typeof AuthenticatedDashboardProdukRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
  }
}

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardProdukRoute: typeof AuthenticatedDashboardProdukRoute
  AuthenticatedDashboardProfilRoute: typeof AuthenticatedDashboardProfilRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardProdukRoute: AuthenticatedDashboardProdukRoute,
    AuthenticatedDashboardProfilRoute: AuthenticatedDashboardProfilRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface AdminRouteChildren {
  AdminHeroRoute: typeof AdminHeroRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminHeroRoute: AdminHeroRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  ArtikelRoute: ArtikelRoute,
  AuthRoute: AuthRoute,
  DirektoriRoute: DirektoriRoute,
  EventRoute: EventRoute,
  MarketplaceRoute: MarketplaceRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminLoginRoute: AdminLoginRoute,
  UmkmSlugRoute: UmkmSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
